package x46010.teamb.srs;


/**
 * Student class contains information about each of the 
 * student objects.
 * 
 * @author William Crews
 * @version 0.1
 */

public class Student {
	
	private int studentID;
	private String firstName;
	private String lastName;
	private String address;
	private String city;
	private String state;
	private String zip;
	private String password = null;
	ArrayList<String> courseList = new ArrayList<String>();
	
	/**
	 * Constructor
	 *
	 * @param studentID			Student ID generated by system when account is created
	 * @param firstName			Students First Name
	 * @param lastName			Students Last Name
	 * @param address			Street Address of student
	 * @param state				State, two letter code representing state
	 * @param zip				Zip code of student
	 * @param password			Password student has chosen for account 
	 */
	public Student(int studentID, String firstName, String lastName, 
	           String address, String city, String state, String zip, 
	           String password) {
		
		this.studentID = studentID;
		this.firstName = firstName;
		this.lastName = lastName;
		this.address = address;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.password = password;
		this.courseList = null;
	}
	
	public Student(String[] fileRecord) {
		
		this.studentID = Integer.parseInt(fileRecord[0]);
		this.firstName = fileRecord[1].trim();
		this.lastName = fileRecord[2].trim();
		this.address = fileRecord[3];
		this.city = fileRecord[4];
		this.state = fileRecord[5];
		this.zip = fileRecord[6];
		this.password = fileRecord[7];
	}
	
}